#ifndef VTX_TYPE_H
#define VTX_TYPE_H

#include <stdlib.h>

#define N_LEGS      12

/* 
 * struct: vtx_element
 *  information about each vertex type
 *  vertex information is generated by the python script
 *
 *  parameters:
 *      (int) indx: index of the vertex
 *      (int) type: vertex type 
 *      (int *) spin: spin value of each leg of the vertex (length N_LEGS)
 *      (int ***) new_vtx_type: vertex type by flipping spins in li
 *          (length x N_LEGS x N_LEGS)
 *      (double) H: Hamiltonian matrix element for the vertex 
 */
typedef struct vtx_type
{
    int indx;
    int type;
    int spin[N_LEGS];
    int new_vtx_type[2];
    double H;
} vtx_element;

#endif // VTX_TYPE_H
